name: seom_v2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  carousel_slider: ^4.2.0
  credit_card_type_detector: ^2.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localization: ^0.1.9
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  http: ^0.13.5
  http_interceptor: ^1.0.2
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kt_dart: ^1.0.0
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  mocktail: ^0.3.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/presentation/core/assets/
    - lib/presentation/core/assets/logos/
